### ISSUE TITLE
Doesn't un-zoom when you invoke power-zoom to go back to previous config

### ISSUE THREAD

**Issue by macintacos** [jaclu/tmux-power-zoom#1]
I had thought that the way this should work is that `<prefix> + Z` would bring you to a zoomed view of the pane you're in, and if you didn't split anything in there, pressing `<prefix> + Z` again would un-zoom things. It doesn't seem to do that - I just get an error saying that it can't zoom the only pane in the window.

Am I doing something wrong? Is there another key combo I'm supposed to press?

I'm on macOS 12.4, running tmux 3.3, using Fish as my main shell (if that helps).

**Comment by jaclu** [comment]
The error msg you mention is normally displayed if an attempt Is made to power zoom the only pane in a window. When un-zooming it should not be checked.

I use zsh and have no experience with Fish, but I doubt this would be Fish-related. But I guess nothing is impossible, hopefully logging what happens will show what is going wrong.

If you could visit `scripts/utils.sh` and uncomment the line: `log_file="/tmp/$plugin_name.log"`
Then either reload your tmux config or just run `~/.tmux/plugins/tmux-power-zoom/power-zoom.tmux` in order to get an initial printout of what settings have been picked up.
If you could post what you get in the log file when trying to un-zoom, that should hopefully give me what I need to investigate what is going wrong.

**Comment by macintacos** [comment]
Sure thing! Here's the output in the log after a reload of my config, as requested:

```
[23:02:25] 
[23:02:25] Wed Jun  8 23:02:25 EDT 2022
[23:02:25] trigger_key=[m]
[23:02:25] Converted incorrect negative [No] to 1
[23:02:25] without_prefix=[0]
[23:02:25] Converted incorrect negative [No] to 1
[23:02:25] mouse_zoom=[0]
[23:02:25] Converted incorrect negative [No] to 1
[23:02:25] use_notes=[0]
[23:02:25] Menus bound to: <prefix> m
```

**Comment by macintacos** [comment]
And here's some additional output after I try to zoom (which succeeds) and then I immediately trigger it again (which errors):

```
[23:04:18] Checking for this place-holder: [=== POWER ZOOM === place-holder for pane: %56]
[23:04:18] Zoom active pane to new window
[23:04:20] Checking for this place-holder: [=== POWER ZOOM === place-holder for pane: %56]
[23:04:20] ERROR: Can't zoom only pane in a window
```

**Comment by macintacos** [comment]
Taking a look at this closer, since I didn't realize it was just a bash script 🙂 

I zoomed into a window and am running each command one by one, and it seems like the "stub" name for the pane that seems like it should should be left in the previous window isn't in the output:

```
bash-5.1$ tmux list-panes -a -F "#D #T"
%16  ~/GitLocal/Play/dotfiles
%55 .tmux.conf (~/GitLocal/Play/dotfiles/rc) - NVIM
%53  ~/GitLocal/Play/dotfiles
%60 bash ~/GitLocal/Play/dotfiles
```

In the above instance, `%60` is the window/pane that was zoomed. I think there should also be another pane with `=== POWER ZOOM ===` in its name, with the same `%60` in its title, and because it seemingly doesn't exist, we skip strait to the call to see if we have more than one pane, and fail. Ran the same command as above but with another `#W` just to be sure:

```
bash-5.1$ tmux list-panes -a -F "#D #T #W"
%16  ~/GitLocal/Play/dotfiles fish
%55 .tmux.conf (~/GitLocal/Play/dotfiles/rc) - NVIM nvim
%53  ~/GitLocal/Play/dotfiles fish
%60 bash ~/GitLocal/Play/dotfiles **POWER ZOOM**  ~/GitLocal/Play/dotfiles (%60)
```

I will say that apparently I'm running `tmux` 3.3, which was just released a week ago. Perhaps a `tmux` command power-zoom is relying on has changed?

**Comment by readysloth** [comment]
Can confirm that I experience it too

**Comment by jaclu** [comment]
> Can confirm that I experience it too

I fixed this back when it was reported, but totally forgot to close the issue, will do a deep dig and see if I can find any remaining issues, will give an update tomorrow (its late now my time)

**Comment by jaclu** [comment]
> Can confirm that I experience it too

It took a while to go through all supported versions, but now I have tested these:
2.6     2.7     2.8     2.9     2.9a    3.0     3.0a    3.1     3.1a    3.1b    3.1c    3.2     3.2a    3.3     3.3a

In all of them, zooming and un-zooming worked as expected for me.

What version are you using? Do you use any non-standard configs, that might have unintended side effects?

**Comment by readysloth** [comment]
I use `tmux 3.3a`, my config and log is below.
Can`t get, what can cause side-effects.

I power-zoom pane, get new window and when i want to zoom back plugin says "Can't unzoom only pane in window"...

```
[22:07:12] trigger_key=[Z]
[22:07:16] Checking for this place-holder: [=== POWER ZOOM === place-holder for pane: %20]
[22:07:16] Zoom active pane to new window
[22:07:18] Checking for this place-holder: [=== POWER ZOOM === place-holder for pane: %20]
[22:07:18] ERROR: Can't zoom only pane in a window
```

```
set -g prefix C-a

set-option -g default-shell /bin/fish

bind C-a send-prefix
unbind C-b
set -sg escape-time 1
set -g base-index 1
setw -g pane-base-index 1
setw -g repeat-time 1000
bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c      "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g default-terminal "screen-256color"
set-window-option -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @sidebar-tree-command 'tree -C'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'jaclu/tmux-power-zoom'

set -g status-right ''


set -g @plugin 'tmux-plugins/tmux-battery'
set -g status-right '#{prefix_highlight} | #{cpu_bg_color} CPU: #{cpu_icon} #{cpu_percentage} | #{battery_status_bg} Batt: #{battery_icon} #{battery_percentage} #{battery_remain} | %a %h-%d %H:%M '
set -g status-right-length '150'

set -g @plugin 'tmux-plugins/tmux-prefix-highlight'


run '~/.tmux/plugins/tpm/tpm'

```

**Comment by jaclu** [comment]
I tested your config, found that I needed fish, so I installed it, and with that installed I also get the error.
I will dig into it, probably something related to fish that I need to take into account, shouldn't be too hard to find.

**Comment by jaclu** [comment]
Ok now it should work fine with fish, not to go into a shell war, but the fact that fish does not follow posix standards for basic stuff like loops was rather unexpected :)

This was just one of the unexpected bullets I struggled with

while true; do
   echo Weeee
done

# becomes

while true
   echo Weeeeeee
end

luckily i could wrap the loop using  bash -c "do loop here" so it will still work with bash/zsh

Let me know if this isn't resolved now :)

**Comment by readysloth** [comment]
Wow, cool, it works!
I didn't expect that fish would cause any problems. I prefer bash for scripting too :)

Thank you, your plugin is very cool!

**Comment by jaclu** [comment]
Appreciated!
I guess I will close this issue for now
